from pydantic import BaseModel, Field
from typing import Optional

class AgentInput(BaseModel):
    """
    Represents the input data for an agent.
    """
    user_query: str = Field(..., description="The user's query or request.")

class AgentOutput(BaseModel):
    """
    Represents the output data from an agent.
    """
    final_answer: str = Field(..., description="The final answer generated by the agent.")
    chain_of_thought: Optional[str] = Field(
        None,
        description="The chain-of-thought used by the agent, if stored."
    )